# 4.1 Exercise on Functions (Workshop 0)
Task 1 — Unit Converter


In [ ]:
def convert_units():
    """
    Convert between different units of measurement.
    Supports length, weight and volume conversions.
    """

    try:
        print("Choose conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = int(input("Enter choice: "))
        value = float(input("Enter value to convert: "))

        if choice == 1:
            print("1. meters → feet")
            print("2. feet → meters")
            sub = int(input("Select option: "))

            if sub == 1:
                result = value * 3.28084
                print("Feet:", result)
            elif sub == 2:
                result = value / 3.28084
                print("Meters:", result)

        elif choice == 2:
            print("1. kg → lbs")
            print("2. lbs → kg")
            sub = int(input("Select option: "))

            if sub == 1:
                print("Pounds:", value * 2.20462)
            elif sub == 2:
                print("Kilograms:", value / 2.20462)

        elif choice == 3:
            print("1. liters → gallons")
            print("2. gallons → liters")
            sub = int(input("Select option: "))

            if sub == 1:
                print("Gallons:", value * 0.264172)
            elif sub == 2:
                print("Liters:", value / 0.264172)

        else:
            print("Invalid choice")

    except ValueError:
        print("Invalid input. Please enter numeric values.")

convert_units()


Choose conversion type:
1. Length
2. Weight
3. Volume
Enter choice: 2
Enter value to convert: 10
1. kg → lbs
2. lbs → kg
Select option: 1
Pounds: 22.0462


Task 2 — Mathematical Operations on List

In [ ]:
def find_sum(numbers):
    return sum(numbers)

def find_average(numbers):
    return sum(numbers) / len(numbers)

def find_max(numbers):
    return max(numbers)

def find_min(numbers):
    return min(numbers)

try:
    nums = list(map(float, input("Enter numbers separated by space: ").split()))

    print("Choose operation:")
    print("1 Sum")
    print("2 Average")
    print("3 Maximum")
    print("4 Minimum")

    choice = int(input("Choice: "))

    if choice == 1:
        print("Sum:", find_sum(nums))
    elif choice == 2:
        print("Average:", find_average(nums))
    elif choice == 3:
        print("Max:", find_max(nums))
    elif choice == 4:
        print("Min:", find_min(nums))

except:
    print("Invalid input")


Enter numbers separated by space: 10
Choose operation:
1 Sum
2 Average
3 Maximum
4 Minimum
Choice: 2
Average: 10.0


# 4.2 List Manipulation
1. Extract Every Other Element

In [ ]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))


[1, 3, 5]


2. Slice Sublist

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([10,20,30,40,50],1,3))


[20, 30, 40]


# Nested List Exercises
Sum of Nested List

In [ ]:
def sum_nested(lst):
    total = 0
    for i in lst:
        if isinstance(i, list):
            total += sum_nested(i)
        else:
            total += i
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))


21


Remove Element

In [ ]:
def remove_element(lst, elem):
    result = []
    for i in lst:
        if isinstance(i, list):
            result.append(remove_element(i, elem))
        elif i != elem:
            result.append(i)
    return result

print(remove_element([[1,2],[3,2],[4,5]],2))


[[1], [3], [4, 5]]


Find Maximum

In [ ]:
def find_max(lst):
    maximum = float('-inf')

    for i in lst:
        if isinstance(i, list):
            maximum = max(maximum, find_max(i))
        else:
            maximum = max(maximum, i)

    return maximum

print(find_max([[1,2],[3,[4,5]],6]))


6


Count Occurrences

In [ ]:
def count_occurrences(lst, elem):
    count = 0

    for i in lst:
        if isinstance(i, list):
            count += count_occurrences(i, elem)
        elif i == elem:
            count += 1

    return count

print(count_occurrences([[1,2],[2,3],[2,4]],2))


3


Flatten Nested List

In [ ]:
def deep_flatten(lst):
    result = []

    for i in lst:
        if isinstance(i, list):
            result.extend(deep_flatten(i))
        else:
            result.append(i)

    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))


[1, 2, 3, 4, 5, 6, 7, 8]


Average of Nested List

In [ ]:
def average_nested(lst):

    flat = deep_flatten(lst)
    return sum(flat)/len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))


3.5


# NumPy Section
Problem 1 — Array Creation

In [ ]:
import numpy as np


In [ ]:
a = np.empty((2,2))
b = np.ones((4,2))
c = np.full((3,3),7)

d = np.zeros_like(c)
e = np.ones_like(c)

new_list = [1,2,3,4]
f = np.array(new_list)

print(a,b,c,d,e,f)


[[5.18827201e-315 0.00000000e+000]
 [5.19284970e-315 5.19284970e-315]] [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] [[7 7 7]
 [7 7 7]
 [7 7 7]] [[0 0 0]
 [0 0 0]
 [0 0 0]] [[1 1 1]
 [1 1 1]
 [1 1 1]] [1 2 3 4]


Problem 2 — Array Manipulation

In [ ]:
a = np.arange(10,50)

b = np.arange(9).reshape(3,3)

c = np.eye(3)

d = np.random.random(30)
print("Mean:", d.mean())

e = np.random.random((10,10))
print("Min:", e.min(), "Max:", e.max())

z = np.zeros(10)
z[4] = 1

arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

border = np.ones((5,5))
border[1:-1,1:-1] = 0

checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1


Mean: 0.5539700766307754
Min: 0.0003165300896300627 Max: 0.9940623889520285
[0 4 0 0 2 1]


Problem 3 — Array Operations

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x+y)
print(x-y)

print(x*3)

print(x**2)

print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))

print(np.vstack((x,y)))
print(np.column_stack((v,w)))


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


Problem 4 — Matrix Operations

In [1]:
import numpy as np

In [16]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_check = np.round(np.dot(A, A_inv))
print("1. A × A⁻¹ = I (rounded):\n", identity_check)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB == BA?", np.array_equal(AB, BA))

AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)^T:\n", AB_T)
print("   B^T × A^T:\n", BT_AT)
print("   Equal?", np.array_equal(AB_T, BT_AT))

1. A × A⁻¹ = I (rounded):
 [[1. 0.]
 [0. 1.]]

2. AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   AB == BA? False

3. (AB)^T:
 [[23 51]
 [13 29]]
   B^T × A^T:
 [[23 51]
 [13 29]]
   Equal? True


In [6]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

# Inverse of A
A_inv = np.linalg.inv(A)

# Solve X
X = np.dot(A_inv,B)

print("Solution [x,y,z] =")
print(X)

Solution [x,y,z] =
[ 2.  1. -2.]


In [7]:
solution = np.linalg.inv(A).dot(B)

print("Solution:")
print(solution)

Solution:
[ 2.  1. -2.]


In [9]:
import time

In [15]:
import time
import numpy as np

SIZE = 1_000_000
a_list = list(range(SIZE))
b_list = list(range(SIZE))
a_np = np.arange(SIZE, dtype=float)
b_np = np.arange(SIZE, dtype=float)

print("-" * 60)
print(f"{'Operation':<25} {'Python List':>12} {'NumPy':>10} {'Speedup':>8}")
print("-" * 60)

t0 = time.time()
result = [a_list[i] + b_list[i] for i in range(SIZE)]
t_list_add = time.time() - t0
t0 = time.time()
result = a_np + b_np
t_np_add = time.time() - t0
print(f"{'Addition':<25} {t_list_add:>11.4f}s {t_np_add:>9.4f}s {t_list_add/t_np_add:>7.1f}x")

t0 = time.time()
result = [a_list[i] * b_list[i] for i in range(SIZE)]
t_list_mul = time.time() - t0
t0 = time.time()
result = a_np * b_np
t_np_mul = time.time() - t0
print(f"{'Multiplication':<25} {t_list_mul:>11.4f}s {t_np_mul:>9.4f}s {t_list_mul/t_np_mul:>7.1f}x")

t0 = time.time()
dot_list = sum(a_list[i] * b_list[i] for i in range(SIZE))
t_list_dot = time.time() - t0
t0 = time.time()
dot_np = np.dot(a_np, b_np)
t_np_dot = time.time() - t0
print(f"{'Dot Product':<25} {t_list_dot:>11.4f}s {t_np_dot:>9.4f}s {t_list_dot/t_np_dot:>7.1f}x")

MSIZE = 200
m_list = [[1.0]*MSIZE for _ in range(MSIZE)]
m_np_a = np.ones((MSIZE, MSIZE))
m_np_b = np.ones((MSIZE, MSIZE))

t0 = time.time()
result_mat_list = [[sum(m_list[i][k] * m_list[k][j] for k in range(MSIZE))
                    for j in range(MSIZE)] for i in range(MSIZE)]
t_list_mat = time.time() - t0
t0 = time.time()
result_mat_np = np.dot(m_np_a, m_np_b)
t_np_mat = time.time() - t0
print(f"{'Matrix Multiply (200x200)':<25} {t_list_mat:>11.4f}s {t_np_mat:>9.4f}s {t_list_mat/t_np_mat:>7.1f}x")

print("-" * 60)

------------------------------------------------------------
Operation                  Python List      NumPy  Speedup
------------------------------------------------------------
Addition                       0.1170s    0.0187s     6.3x
Multiplication                 0.1298s    0.0173s     7.5x
Dot Product                    0.1500s    0.0017s    90.0x
Matrix Multiply (200x200)      0.8419s    0.0010s   821.8x
------------------------------------------------------------
